### ISSUE TITLE
Any plans to upgrade required Guzzle version

### ISSUE THREAD

**Issue by carltondickson** [ElasticEmail/ElasticEmail.WebApiClient-php#12]
HI,

Just wondering if there are plans to upgrade the required Guzzle version. We're moving to Laravel 8 which requires Guzzle 7 which seems to clash with the existing requirement of 6. Will try and fork and then upgrade for now.

**Comment by muzammilaskari** [comment]
Hi,
I have same issue, I am working on laravel 8, I am unable to install this will Guzzle 7

**Comment by ElasticEmail** [comment]
Hi guys, we bumped up Guzzle version.

**Comment by carltondickson** [comment]
❤️

**Comment by devsalsa** [comment]
@ElasticEmail a version bump would be great too. I don't see any new release.

**Comment by ElasticEmail** [comment]
@devsalsa dev-master is the tag you are looking for :)

**Comment by devsalsa** [comment]
@ElasticEmail this is not a stable tag. We only use stable packages :-)
