### ISSUE TITLE
Undefined property: stdClass::$data

### ISSUE THREAD

**Issue by carltondickson** [ElasticEmail/ElasticEmail.WebApiClient-php#6]
Calling API endpoints which result in `{"success": true}` being returned appear to throw the error
**Undefined property: stdClass::$data**

e.g. `$elastic_email_client->Contact->ChangeStatus('Transactional', null, ['email@domain.com']);`

```
# ./vendor/elastic-email/web-api-client/src/ElasticEmailClient/ElasticRequest.php
if (!$resp->success) {
	throw new \Exception($resp->error);
}

// This property doesn't always exist
// http://api.elasticemail.com/public/help#Contact_ChangeStatus
return $resp->data;
```

Would something like this work?

`return (isset($resp->data) ? $resp->data : $resp);`

**Comment by ppodolak** [comment]
@carltondickson  Hi,
Thanks for pointing that out, ive just deployed a fix for that.

**Comment by carltondickson** [comment]
Perfect, thanks

**Comment by franko108** [comment]
Hi, 
the same bug seems to be active again. (installed via composer)
I've got error:
``PHP Notice:  Undefined property: stdClass::$data in /var/www/html/develop/phpmailer/elasticmail/vendor/elastic-email/web-api-client/src/ElasticEmailClient/ElasticRequest.php on line 72
``
Same patch is helping:
`` if (isset($resp->data)) { return $resp->data; }``

However, if I do `var_dump($resp)` - I've got:
``object(stdClass)#216 (1) {
  ["success"]=>
  bool(true)
}
``
(looks fine). This is happening when calling:  
 `$client->Contact->QuickAdd([email@test.com]);`  
Still, even after patch, no error is returned but my contact isn't added to the contact list.  
Hopefully I'm adding param (email) on correct manner?  
Not sure that I can do with free account?

Finally, it would be nice to update the present API examples on [manual](https://help.elasticemail.com/en/articles/2295186-php-api-integration-library)  
Examples are incorrect, apostrophes and so on.
